package main

import (
	"bytes"
	"fmt"
	"text/template"
)

const schemaTemplate = `// Code generated by "go-validation"; DO NOT EDIT.
package {{ .PackageName }}

import (
	"errors"
	"regexp"
	"strings"

	"github.com/spf13/cast"
)

// Generated user schema based on dynamic rules.
func New{{.StructName}}Schema(u {{.StructName}}) {{.StructName}}Schema {
	return {{.StructName}}Schema{
		rules: []SchemaRule{
			{{range .Rules}}
			SchemaRule{
				Name:      "{{.Name}}",
				Type:      {{.Type}},
				Field1:    "{{.Field1}}",
				Field2:    "{{.Field2}}",
				Cond1:     {{.Cond1}},
				Cond2:     {{.Cond2}},
			},
			{{end}}
		},
	}
}

type {{.StructName}}Schema struct {
	{{.StructName}}
	rules []SchemaRule
}

func (s {{.StructName}}Schema) Validate() (messages []string) {
	for _, rule := range s.rules {
		if err := rule.Validate(); err != nil {
			messages = append(messages, err.Error())
		}
	}
	return messages
}

// Schema rule types with their validators
type SchemaRule struct {
	Name      string
	Type      ruleType
	Field1    string
	Field2    string
	Cond1     *Value
	Cond2     *Value
}

{{range .Validators}}
func {{.Name}}(field string, value any, cond any) error {
	{{.Implementation}}
}
{{end}}

{{range .Errors}}
func {{.Name}}(field1, value1, field2, value2 string) error {
	msg := "{{.Message}}"
	msg = strings.ReplaceAll(msg, ":field1", field1)
	msg = strings.ReplaceAll(msg, ":value1", value1)
	msg = strings.ReplaceAll(msg, ":field2", field2)
	msg = strings.ReplaceAll(msg, ":value2", value2)
	return errors.New(msg)
}
{{end}}
`

type SchemaData struct {
	StructName string
	Rules      []SchemaRuleData
	Validators []ValidatorData
	Errors     []ErrorData
}

type SchemaRuleData struct {
	Name   string
	Type   string
	Field1 string
	Field2 string
	Cond1  string
	Cond2  string
}

type ValidatorData struct {
	Name           string
	Implementation string
}

type ErrorData struct {
	Name    string
	Message string
}

func TestTmpl() {
	// Sample data for template
	data := SchemaData{
		StructName: "User",
		Rules: []SchemaRuleData{
			{Name: "ID", Type: "_Gov_RulePresence", Field1: "ID", Field2: "", Cond1: "1", Cond2: ""},
			{Name: "Name", Type: "_Gov_RulePresence", Field1: "Name", Field2: "", Cond1: `"John"`, Cond2: ""},
			// Add more rules as needed
		},
		Validators: []ValidatorData{
			{Name: "_Gov_Required", Implementation: `if cast.ToString(value) == "" { return errors.New("Field is required.") } return nil`},
			{Name: "_Gov_Email", Implementation: `if !regexp.MustCompile(` + "`" + `^\\S+@\\S+\\.\\S+$` + "`" + `).MatchString(cast.ToString(value)) { return errors.New("Invalid email format.") } return nil`},
		},
		Errors: []ErrorData{
			{Name: "_Gov_ErrorRequired", Message: "The :field field is required."},
			{Name: "_Gov_ErrorEmail", Message: "The :field field must be a valid email address."},
		},
	}

	// Parse and execute the template
	tmpl, err := template.New("schema").Parse(schemaTemplate)
	if err != nil {
		panic(err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		panic(err)
	}

	fmt.Println(buf.String())
}
